### PR TITLE
Add attribute name to the Component

### PR DESCRIPTION
**Pull request by Jakub-Fajkus**
I kinda miss the name in our components... Naming like "the fifth component of type engine" seems kinda silly.

I'he updated the Class diagram in the wiki PR as well.

### CODE REVIEW

**Comment by tomasedl** [comment]
Maybe add some attribute for the version of a component? something like component: engine, version: 1, car: None
or how will look like our naming for each component while a new version will be added

**Comment by Jakub-Fajkus** [comment]
I've discussed this with somebady and we agreed that the name will be enough. You can always add versioning to the name

**Review by tomasedl — APPROVED** [review]

**Review by khecova — APPROVED** [review]
In this case, I should add findByName() into the ComponentDao ... or not?

**Comment by Jakub-Fajkus** [comment]
> In this case, I should add findByName() into the ComponentDao ... or not?

Im not a big fan of "useless" methods that are written just because we might need them later. I would add the method when we find out that we need it...

**Pull request merged**
